// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_UhrHoPJthItuR0tkLd6HvHfASc1i4o',
    appId: '1:578206380982:web:4837bb90b0cbb5a67f8717',
    messagingSenderId: '578206380982',
    projectId: 'bonjaur-demo',
    authDomain: 'bonjaur-demo.firebaseapp.com',
    storageBucket: 'bonjaur-demo.appspot.com',
    measurementId: 'G-KEKCYV000R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhZQUcX6eAv7jW7rPjlbASUm_eJlIuScU',
    appId: '1:578206380982:android:e0d9c64b0be528a67f8717',
    messagingSenderId: '578206380982',
    projectId: 'bonjaur-demo',
    storageBucket: 'bonjaur-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzkpqmhf3KqoUnWNnF0uYY3VP1_owbDPE',
    appId: '1:578206380982:ios:b80a2bf10fa1b0877f8717',
    messagingSenderId: '578206380982',
    projectId: 'bonjaur-demo',
    storageBucket: 'bonjaur-demo.appspot.com',
    iosClientId: '578206380982-eiqi6te628kjs9v1qja425elkrm1hmlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.bonjaurDemo',
  );
}
